tap "felixkratz/formulae"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "bat"
brew "bitlbee"
brew "gh"
brew "pyenv"
brew "ripgrep"
brew "sapling"
brew "weechat"
brew "zlib"
brew "felixkratz/formulae/borders"
brew "koekeishiya/formulae/skhd", args: ["HEAD"]
brew "koekeishiya/formulae/yabai"
cask "github"
cask "vscodium"
cask "warp"
