#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa

border_padding=20

# global settings

yabai -m config                                     \
    mouse_follows_focus          off                \
    focus_follows_mouse          off                \
    window_origin_display        default            \
    window_placement             second_child       \
    window_zoom_persist          on                 \
    window_topmost               off                \
    window_shadow                on                 \
    window_animation_duration    1.0                \
    window_opacity_duration      0.0                \
    active_window_opacity        1.0                \
    normal_window_opacity        0.90               \
    window_opacity               on                 \
    insert_feedback_color        0xffd75f5f         \
    split_ratio                  0.5                \
    split_type                   auto               \
    auto_balance                 off                \
    top_padding                  ${border_padding}  \
    bottom_padding               ${border_padding}  \
    left_padding                 ${border_padding}  \
    right_padding                ${border_padding}  \
    window_gap                   ${border_padding}  \
    layout                       bsp                \
    mouse_modifier               cmd                \
    mouse_action1                resize             \
    mouse_drop_action            swap

# Make certain apps unmanaged/floating
yabai -m rule --add app="^Calculator$" manage="off"
yabai -m rule --add app="^Stickies$" manage="off"
yabai -m rule --add app="^System Settings$" manage="off"
yabai -m rule --add app="^.*Time Out$" manage="off"
yabai -m rule --add app="^Vitamin.*R$" manage="off"
yabai -m rule --add app="^Managed Software Center$" manage="off"
yabai -m rule --add app="^Finder$" manage="off"


# Music Apps are always full screen
# spotify_label="fullscreen-spotify"
# yabai -m rule   --add label="${spotify_label}" app="^Spotify$" manage="off" native-fullscreen="on"
# yabai -m signal --add event="window_focused"   app="^Spotify$" action="yabai -m rule --apply ${spotify_label}"

# di_label="digitally-imported"
# yabai -m rule   --add label="${di_label}"      title="^.*digitally.*imported.*$" manage="off" native-fullscreen="on"
# yabai -m signal --add event="window_focused"   title="^.*digitally.*imported.*$" action="yabai -m rule --apply ${di_label}"

# Make everything else full screen?
# yabai -m rule   --add label="full-screen-everything" app=".*" manage="off" native-fullscreen="on"

# Janky Borders
borders active_color=0xffe149a7  width="${border_padding}" hidpi=on &
