#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa


# global settings
yabai -m config                                 \
    mouse_follows_focus          on		        \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    1.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.5            \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  10             \
    bottom_padding               10             \
    left_padding                 10             \
    right_padding                10             \
    window_gap                   20             \
    layout                       bsp		    \
    mouse_modifier               cmd		    \
    mouse_action1                resize         \
    mouse_drop_action            swap


yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^DI.FM$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^Vitamin.*R.*$" manage=off
yabai -m rule --add app="^Time.*Out$" manage=off

borders active_color=0xffe149a7  width=10.0 hidpi=on &
