# Whaley's config
# I try to do as much with the keyboard as I can, so there's a few bespoke exec-and-forget items in modes as well

# Tip: if you need to debug why an exec-and-forget command isn't working, try using
# ` exec > /tmp/aerospace.log 2>&1 ; env`
# before your command to redirect all stdout/stderr to a log file and also dump your environment variables

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    'exec-and-forget borders active_color="glow(0x88CFF69B4)" inactive_color="glow(0x88FFFFF0)" width=20'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers                         = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodness#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Setup environmental variables
[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = "${HOME}/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}"

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# [key-mapping.key-notation-to-key-code]
# meh = 'ctr-alt-shift'
# hyper = 'ctrl-alt-shift-cmd'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps.inner]
horizontal    = 40
vertical      = 40
[gaps.outer]
left          = 20
right         = 20
bottom        = 20
top           = 20

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): mode.main.binding = {}
[mode.main.binding]

# All possible keys
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-shift-comma        = 'layout floating tiling' #toggle floating / tiling for a singlne window
ctrl-alt-shift-period       = 'layout accordion horizontal vertical'
ctrl-alt-shift-slash        = 'layout tiles horizontal vertical'

ctrl-alt-shift-f            = 'fullscreen' #toggle fullscreen for a window

# See: https://nikitabobko.github.io/AeroSpace/commands#flatten-workspace-tree
cmd-ctrl-alt-shift-esc          = 'flatten-workspace-tree' #reset layout

# See: https://nikitabobko.github.io/AeroSpace/commands#balance-sizes
ctrl-alt-shift-esc          = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-shift-g            = 'focus --dfs-index 0' #first window
ctrl-alt-shift-j            = 'focus left   --boundaries all-monitors-outer-frame'
ctrl-alt-shift-k            = 'focus down   --boundaries all-monitors-outer-frame'
ctrl-alt-shift-i            = 'focus up     --boundaries all-monitors-outer-frame'
ctrl-alt-shift-l            = 'focus right  --boundaries all-monitors-outer-frame'

ctrl-alt-shift-left         = 'swap left'
ctrl-alt-shift-down         = 'swap down'
ctrl-alt-shift-up           = 'swap up'
ctrl-alt-shift-right        = 'swap right'

cmd-ctrl-alt-shift-j        = 'move left --boundaries all-monitors-outer-frame'
cmd-ctrl-alt-shift-k        = 'move down --boundaries all-monitors-outer-frame'
cmd-ctrl-alt-shift-i        = 'move up --boundaries all-monitors-outer-frame'
cmd-ctrl-alt-shift-l        = 'move right --boundaries all-monitors-outer-frame'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
cmd-ctrl-alt-shift-left     = 'join-with left'
cmd-ctrl-alt-shift-down     = 'join-with down'
cmd-ctrl-alt-shift-up       = 'join-with up'
cmd-ctrl-alt-shift-right    = 'join-with right'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus-monitor
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-monitor
ctrl-alt-shift-m            = 'focus-monitor next --wrap-around'
cmd-ctrl-alt-shift-m        = 'move-node-to-monitor next --wrap-around'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-shift-minus        = 'resize smart          -100'
ctrl-alt-shift-equal        = 'resize smart          +100'
ctrl-alt-shift-cmd-minus    = 'resize smart-opposite -100'
ctrl-alt-shift-cmd-equal    = 'resize smart-opposite +100'

# Move between workspaces
ctrl-alt-shift-tab          = 'workspace-back-and-forth'

# Modes
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-alt-shift-o            = 'mode open'
ctrl-alt-shift-u            = 'mode util'
ctrl-alt-shift-b            = 'mode borders'
ctrl-alt-shift-w            = 'mode workspaces' 


#######################################
# Mode: Workspace Manipulation
#######################################
[mode.workspaces.binding]
esc                         = 'mode main'

# Workspaces
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
o                           = 'workspace organize'
ctrl-alt-shift-o            = 'move-node-to-workspace organize --focus-follows-window'

d                           = 'workspace dev'
ctrl-alt-shift-d            = 'move-node-to-workspace dev --focus-follows-window'

c                           = 'workspace communicate'
ctrl-alt-shift-c            = 'move-node-to-workspace communicate --focus-follows-window'

m                           = 'workspace music'    
ctrl-alt-shift-m            = 'move-node-to-workspace music --focus-follows-window'

r                           = 'workspace research'
ctrl-alt-shift-r            = 'move-node-to-workspace research --focus-follows-window'

ctrl-alt-shift-left         = 'workspace --wrap-around prev'
ctrl-alt-shift-right        = 'workspace --wrap-around next'

cmd-ctrl-alt-shift-left     = 'move-node-to-workspace --wrap-around --focus-follows-window prev'
cmd-ctrl-alt-shift-right    = 'move-node-to-workspace --wrap-around --focus-follows-window next'

# Move between workspaces
ctrl-alt-shift-tab          = 'workspace-back-and-forth'

# Still allow focus between windows with hjkl even when in workspace mode
ctrl-alt-shift-j            = 'focus left   --boundaries all-monitors-outer-frame'
ctrl-alt-shift-k            = 'focus down   --boundaries all-monitors-outer-frame'
ctrl-alt-shift-i            = 'focus up     --boundaries all-monitors-outer-frame'
ctrl-alt-shift-l            = 'focus right  --boundaries all-monitors-outer-frame'


#######################################
# Mode: Open Apps and Windows
#######################################
[mode.open.binding]
esc                         = 'mode main'


# Arc
a = ['''exec-and-forget osascript -e '
tell application "Arc"
	make new window
	activate
end tell
'
''', 'mode main']

#  Chrome
c = ['''exec-and-forget osascript -e '
if application "Google Chrome" is running then
    tell application "Google Chrome"
        make new window
    end tell
else
    tell application "Google Chrome"
        activate
    end tell
end if
'
''', 'mode main']

# Open iTerm if needed, or create new window
t =  ['''exec-and-forget osascript -e '
if application "iTerm" is running then
    tell application "iTerm"
        set newWindow to (create window with default profile)
    end tell
else
    tell application "iTerm"
        activate
    end tell
end if
'
''', 'mode main']


# Open Omnifocus in a new window
# Bit of a hack with keyboard shortcuts since 'make new document window' creates a new tab
f = ['''exec-and-forget osascript -e '
if application "Omnifocus" is running then
    tell application "OmniFocus"
        tell default document
            make new document window
        end tell
    end tell
else
    tell application "OmniFocus"
        activate
    end tell
end if
'
''', 'mode main']

# Open a new Kitty OS Window.  Kitty needs allow_remote_control socket_only in its config
k = ['''exec-and-forget osascript -e 'tell application "kitty" to activate' && kitten @ --to "unix:/tmp/kitty-socket-$(pgrep kitty)" launch --type os-window
''', 'mode main']

# Apps with only a single window or can't otherwise support applescript
# e.g. PWA's or Electron apps
#1Password
1 = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py "1Password"', 'mode main']
#Obsidian
o = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py Obsidian', 'mode main']
#Google Chat
g = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py "Google Chat" --app-path "$HOME/Applications/Chrome Apps.localized/Google Chat.app" ', 'mode main']
#Brain.fm
b = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py "Brain.fm"', 'mode main']
#Apple Music
m = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py "Music" --app-path "System/Applications/Music.app"', 'mode main']
#Vitamin R
r = ['exec-and-forget aerospace_open_or_move_to_current_workspace.py "Vitamin-R 4"', 'mode main']



[mode.util.binding]
esc = 'mode main'

r = ['reload-config', 'mode main']

f = ['mode main', 'macos-native-fullscreen'] #make 'mode main' first, since native command must appear last in a list

# Toggle minimize everything on current workspace
# Also restores focus back to the workspace we just minimized everything on
m = ['''exec-and-forget
currentWorkspace=$(aerospace list-workspaces --focused)
for id in $(aerospace list-windows --workspace focused | awk '{print $1}'); do
    aerospace macos-native-minimize --window-id "$id"
done
aerospace workspace "$currentWorkspace"
''', 'mode main']

t = ['''exec-and-forget  aerospace_retile_windows.py''', 'mode main']

# Toggle headpones being connected
# NOTE: This requires giving Aerospace permission to use Bluetooth in System Settings > Privacy and Security > Bluetooth
h = ['''exec-and-forget
toggle_bt.sh "Grey WH-1000XM5"
''', 'mode main']

left    = ['exec-and-forget aerospace_move_to_edge.py left', 'mode main']
right   = ['exec-and-forget aerospace_move_to_edge.py right', 'mode main']
up      = ['exec-and-forget aerospace_move_to_edge.py up', 'mode main']
down    = ['exec-and-forget aerospace_move_to_edge.py down', 'mode main']

[mode.borders.binding]
esc = 'mode main'

#For changing janky borders colors - also restarts it

# pink
p = ['exec-and-forget nohup borders active_color="glow(0x88CFF69B4)" inactive_color="glow(0x88FFFFF0)" width=20 &', 'mode main']

# green
g = ['exec-and-forget nohup borders active_color="glow(0x88ADFF2F)" inactive_color="glow(0x88FFFFF0)" width=20 &', 'mode main']

# blue
b = ['exec-and-forget nohup borders active_color="glow(0x8887CEFA)" inactive_color="glow(0x88FFFFF0)" width=20 &', 'mode main']


###############################################################################
# On-window-detected callbacks
###############################################################################
# [[on-window-detected]]
#     if.app-id = 'com.electron.brain.fm'
#     check-further-callbacks = true
#     run = 'macos-native-fullscreen on'
# [[on-window-detected]]
#     if.app-name-regex-substring = 'di.fm'
#     check-further-callbacks = true
#     run = 'macos-native-fullscreen on'
# [[on-window-detected]]
#     if.app-id = 'com.apple.Music'
#     check-further-callbacks = true
#     run = 'macos-native-fullscreen on'
