macos_option_as_alt both

confirm_os_window_close -1

# THEME
include themes/material-dark.conf

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
# END_KITTY_FONTS

# BEGIN_REMOTE_CONTROL
# allow remote on localhost only
allow_remote_control socket-only
listen_on unix:/tmp/kitty-socket
# END_REMOTE_CONTROL
