#Material Dark

background            #283137
foreground            #eceef0
cursor                #edeeed
selection_background  #657c89
selection_foreground  #eceef0

# Black
color0                #596d78

# Bright Black (Gray)
color8                #b2bdc4

# Red
color1                #eb5f59

# Bright Red
color9                #ef9084

# Green
color2                #8eedb3

# Bright Green
color10               #c5f4cd

# Yellow
color3                #f8d85e

# Bright Yellow
color11               #fae58d

# Blue
color4                #68c1f9

# Bright Blue
color12               #94d5fa

# Magenta
color5                #eb5181

# Bright Magenta
color13               #ee86aa

# Cyan
color6                #8ff8db

# Bright Cyan
color14               #bafaeb

# White
color7                #bafaeb

# Bright White
color15               #fefefe
